head_camera:
  enable_zmq: true
  zmq_port: 55555
  enable_webrtc: false
  webrtc_port: 60001
  type: opencv
  image_shape:
  - 480
  - 1920
  binocular: false
  fps: 60
  video_id: 0
  serial_number: 01.00.00
  physical_path: null
left_wrist_camera:
  enable_zmq: true
  zmq_port: 55556
  enable_webrtc: false
  webrtc_port: 60002
  type: uvc
  image_shape:
  - 480
  - 640
  binocular: false
  fps: 60
  video_id: 2
  serial_number: 200901010001
  physical_path: null
right_wrist_camera:
  enable_zmq: true
  zmq_port: 55557
  enable_webrtc: false
  webrtc_port: 60003
  type: uvc
  image_shape:
  - 480
  - 640
  binocular: false
  fps: 60
  video_id: 4
  serial_number: 200901010002
  physical_path: null
